; PlatformIO Project Configuration File
[platformio]
src_dir = .
default_envs = esp32s3box

; Common settings for all environments can be defined here
[common]
monitor_speed = 115200
extra_lib_dirs = ./shared_lib
build_flags = 
    -D WIFI_SSID=\"YourWiFiSSID\"
    -D WIFI_PASSWORD=\"YourWiFiPassword\"
    -D PAYLOAD_MAX=8
    -D MQTT_SERVER=\"broker.emqx.io\"
    -D MQTT_PORT=1883
    -D MQTT_DATA_TOPIC=\"waste-management-system/data\"
    -D MQTT_COMMAND_TOPIC=\"waste-management-system/command\"

; Camera board configuration
[env:esp32s3box]
platform = espressif32
framework = arduino
board = esp32s3box
monitor_speed = ${common.monitor_speed}

; Source files for camera board
build_src_filter =
    +<MCU_Camera/src/**>

; Libraries
lib_extra_dirs =
    ./MCU_Camera/lib
    ${common.extra_lib_dirs}
lib_deps =
    knolleary/PubSubClient@^2.8

; Build flags for camera board
build_flags =
    ${common.build_flags}
    -D MQTT_CLIENT_ID=\"esp32s3box_camera\"
    -D BOARD_HAS_PSRAM ; Enable PSRAM support
    -D ARDUINO_USB_MODE=1 ; Enable USB functionality
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; Enable USB CDC on boot

board_build.arduino.memory_type = qio_opi ; Use QIO flash mode for better performance

; ------------------------------------------------------------

; Servo board configuration
[env:esp32-s2-saola-1]
platform = espressif32
framework = arduino
board = esp32-s2-saola-1
monitor_speed = ${common.monitor_speed}

; Configure source files for servo boards
build_src_filter =
    +<MCU_Servo/src/**>

; Build flags for servo board
build_flags = 
    ${common.build_flags}
    -D MQTT_CLIENT_ID=\"esp32s2_servo\"

; Libraries
lib_extra_dirs =
    ./MCU_Servo/lib
    ${common.extra_lib_dirs}

lib_deps =
    knolleary/PubSubClient@^2.8
    madhephaestus/ESP32Servo