"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9)5u=z=s9zl3204e+g4xu@_5_i9ven70d6x#xvw*i3dq2vq*xq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "1") == "1"

# 2. Wire ALLOWED_HOSTS to the environment variable.
allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,192.168.137.1")
# ALLOWED_HOSTS = allowed_hosts_env.split(",")
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',           # 
    'django.contrib.auth',            # 
    'django.contrib.contenttypes',    # 
    'django.contrib.sessions',        # 
    'django.contrib.messages',        # 
    'django.contrib.staticfiles',
    'detection',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # Auth
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',      #
                'django.contrib.messages.context_processors.messages', #
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/ 

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles" #

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MQTT Broker Settings (aligned with platformio.ini / ESP32 TCP clients)
MQTT_BROKER_HOST = os.environ.get("MQTT_BROKER_HOST", "broker.emqx.io")
MQTT_BROKER_PORT = int(os.environ.get("MQTT_BROKER_PORT", 1883))
MQTT_TOPIC = os.environ.get("MQTT_TOPIC", "waste-management-system/command")
MQTT_DATA_TOPIC = os.environ.get("MQTT_DATA_TOPIC", "waste-management-system/data")

# ESP32 device ports (camera + servo) are TCP MQTT ports.
# Keep both defaults aligned with platformio.ini common build flags.
MQTT_CAMERA_TCP_PORT = int(os.environ.get("MQTT_CAMERA_TCP_PORT", MQTT_BROKER_PORT))
MQTT_SERVO_TCP_PORT = int(os.environ.get("MQTT_SERVO_TCP_PORT", MQTT_BROKER_PORT))

# Browser (Paho WebSocket) — EMQX public WSS defaults
MQTT_WS_PORT = int(os.environ.get("MQTT_WS_PORT", 8084))
MQTT_WS_USE_SSL = os.environ.get("MQTT_WS_USE_SSL", "true").lower() in ("1", "true", "yes")
MQTT_WS_PATH = os.environ.get("MQTT_WS_PATH", "/mqtt")